language: python
sudo: false
python:
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
  fast_finish: true
services:
  - mysql
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install mysqlclient
  - travis_retry pip install -e .
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
before_script:
  - mysql -e 'create database joule'

script: 
- python manage.py test --pattern="*test*.py"
- coverage run --source='.' manage.py test --pattern="*test*.py"
after_success: coveralls
notifications:
  email: false
  slack: $SLACK_TOKEN
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  
  app: "joulia-webserver"
  env: "joulia-webserver-prod"
  bucket_name: "joulia-webserver-builds"
