language: python
sudo: false
python:
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
  fast_finish: true
services:
  - mysql
  - docker
env:
  global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - GCLOUD_PROJECT_ID="core-song-155902"
    - GCLOUD_ZONE="us-central1-a"
    - GCLOUD_APPLICATION_CREDENTIALS="${PWD}/gcloud-secret.json"
    - GCLOUD_CLUSTER_NAME="joulia"
before_install:
  - openssl aes-256-cbc -K $encrypted_c2865a050002_key -iv $encrypted_c2865a050002_iv -in gcloud-secret.json.enc -out gcloud-secret.json -d
  - ./gcloud-sdk-install.sh
  - source /home/travis/.bashrc
  - ./gcloud-sdk-configure.sh
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install mysqlclient
  - travis_retry pip install -e .
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
before_script:
  - mysql -e 'create database joule'
script: 
- python manage.py test --pattern="*test*.py"
- coverage run --source='.' manage.py test --pattern="*test*.py"
after_success: coveralls
notifications:
  email: false
  slack: $SLACK_TOKEN
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "joulia-webserver"
    env: "joulia-webserver-prod"
    bucket_name: "joulia-webserver-builds"
    on:
      branch: master
  - provider: script
    script: "./deploy_docker.sh"
    on:
      branch: master
  - provider:
    script: "./deploy_kubernetes.sh"
    on:
      branch: master
