version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: joulia
      MYSQL_DATABASE: joulia
      MYSQL_USER: joulia
      MYSQL_PASSWORD: joulia
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db