version: 2.1 # 2.1 required for some orbs.
# change to trigger new workflow: 2

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
  gcp-gcr: circleci/gcp-gcr@0.6.1
  gcp-gke: circleci/gcp-gke@1.0.3

commands:
  # Rolls deployment out to kubernetes cluster.
  deploy-to-kubernetes-cluster:
    parameters:
      gcloud-service-key:
        description: The environment variable to authenticate with.
        type: env_var_name

      google-project-id:
        description: The Project Id containing the cluster.
        type: env_var_name

      cluster:
        description: The Kubernetes cluster to update the deployment in.
        type: env_var_name

      deployment:
        description: The Kubernetes deployment name to deploy to.
        type: string

      namespace:
        description: The namespace the deployment resides in.
        type: string
        default: default

      container:
        description: The container to update in the deployment pods.
        type: string

      image:
        description: Path to image to use for deployment.
        type: string

    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          gcloud-service-key: <<parameters.gcloud-service-key>>
          google-project-id: <<parameters.google-project-id>>
          cluster: $<<parameters.cluster>>
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: $<<parameters.cluster>>
          namespace: <<parameters.namespace>>
          deployment: <<parameters.deployment>>
          container: <<parameters.container>>
          image: <<parameters.image>>
          tag: $CIRCLE_SHA1

jobs:
  # Runs the Play application unit tests using a local postgres instance.
  test:
    docker:
    - image: python:3.5

    working_directory: ~/joulia_webserver

    steps:

    - checkout

    # Install Python dev Dependencies.
    - run:
        name: Install OS Dependencies
        command: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y python-dev
            apt-get install -y python3-dev
            apt-get install -y default-libmysqlclient-dev

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-

    - run:
        name: Install Dependencies
        command: pip install -r requirements.txt

    - save_cache:
        paths:
        - ~/.cache/pip
        key: v2-dependencies-{{ checksum "requirements.txt" }}

    - run:
        name: Run Tests
        command: python manage.py test --pattern="*test*.py"


  # Builds docker container and pushes to Google Container Repository.
  push-image:
    docker:
    - image: google/cloud-sdk

    steps:
    - checkout

    - setup_remote_docker

    - gcp-gcr/gcr-auth:
        gcloud-service-key: GCLOUD_SERVICE_KEY
        google-compute-zone: GOOGLE_COMPUTE_ZONE
        google-project-id: GOOGLE_PROJECT_ID

    - gcp-gcr/build-image:
        google-project-id: GOOGLE_PROJECT_ID
        image: joulia-webserver
        registry-url: gcr.io
        tag: $CIRCLE_SHA1

    - gcp-gcr/push-image:
        google-project-id: GOOGLE_PROJECT_ID
        image: joulia-webserver
        registry-url: gcr.io
        tag: $CIRCLE_SHA1

    - gcp-gcr/tag-image:
        google-project-id: GOOGLE_PROJECT_ID
        image: joulia-webserver
        registry-url: gcr.io
        source-tag: $CIRCLE_SHA1
        target-tag: $CIRCLE_BRANCH

    - gcp-gcr/tag-image:
        google-project-id: GOOGLE_PROJECT_ID
        image: joulia-webserver
        registry-url: gcr.io
        source-tag: $CIRCLE_SHA1
        target-tag: latest

  # Rolls deployment out to kubernetes cluster.
  deploy-webserver-to-prod:
    docker:
      - image: google/cloud-sdk

    steps:
      - deploy-to-kubernetes-cluster:
          deployment: joulia-webserver
          namespace: default

          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-project-id: GOOGLE_PROJECT_ID
          cluster: GOOGLE_CLUSTER_NAME
          container: joulia-webserver
          image: gcr.io/core-song-155902/joulia-webserver

workflows:
  version: 2
  test_and_deploy:
    jobs:
    - test
    - push-image:
        requires:
        - test
        filters:
          branches:
            only:
            - master
    - deploy-webserver-to-prod:
        requires:
          - push-image
        filters:
          branches:
            only:
              - master
