# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Brewhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brewery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewery')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
            ],
        ),
        migrations.CreateModel(
            name='BrewingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BeerStyle')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=False)),
                ('brewhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewhouse')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('recipe_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.RecipeInstance')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.AssetSensor')),
            ],
        ),
        migrations.AddField(
            model_name='brewery',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BrewingCompany'),
        ),
        migrations.AddField(
            model_name='assetsensor',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewhouse'),
        ),
    ]
