# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetsensor',
            old_name='brewery',
            new_name='brewhouse',
        ),
    ]
