# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0002_auto_20170407_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdatapoint',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeseriesdatapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
