# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0003_auto_20170410_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstance',
            name='final_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recipeinstance',
            name='original_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
