# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0004_auto_20160629_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstyle',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
