# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0005_auto_20160629_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstance',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeinstance',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewery'),
        ),
    ]
