# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('brewery', '0008_brewery_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='group',
        ),
        migrations.AddField(
            model_name='brewery',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BrewingCompany'),
        ),
    ]
