# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0009_auto_20160717_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address1', models.CharField(max_length=256, null=True)),
                ('address2', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
