# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0011_timeseriesdatapoint_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cool_temperature',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mashout_temperature',
            field=models.FloatField(default=170.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mashout_time',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='strike_temperature',
            field=models.FloatField(default=162.0),
        ),
    ]
