# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0011_auto_20160720_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsensor',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetsensor',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Brewery'),
        ),
        migrations.AlterField(
            model_name='brewingfacility',
            name='address1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brewingfacility',
            name='address2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brewingfacility',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brewingfacility',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brewingfacility',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
