# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0012_auto_20160720_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='company',
        ),
        migrations.AddField(
            model_name='brewingfacility',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BrewingCompany'),
        ),
    ]
