# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0013_recipe_boil_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JouliaControllerRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.JouliaControllerRelease'),
        ),
    ]
