# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0013_auto_20160721_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brewery',
            new_name='Brewhouse',
        ),
    ]
