# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0014_auto_20160721_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrewingFacility',
            new_name='Brewery',
        ),
        migrations.RenameField(
            model_name='brewhouse',
            old_name='location',
            new_name='brewery',
        ),
    ]
