# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0014_auto_20170723_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotLiquorTun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('heating_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.HeatingElement')),
            ],
        ),
        migrations.CreateModel(
            name='MashTun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('heat_exchanger_conductivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTemperatureDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField()),
                ('zero_resistance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTemperatureDeviceAmplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcc', models.FloatField()),
                ('rtd_top_resistance', models.FloatField()),
                ('amplifier_resistance_a', models.FloatField()),
                ('amplifier_resistance_b', models.FloatField()),
                ('offset_resistance_bottom', models.FloatField()),
                ('offset_resistance_top', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTemperatureDeviceMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_pin', models.IntegerField()),
                ('tau_filter', models.FloatField(default=10.0)),
                ('analog_reference', models.FloatField(default=3.3)),
                ('amplifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceAmplifier')),
                ('rtd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDevice')),
            ],
        ),
        migrations.AddField(
            model_name='mashtun',
            name='temperature_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceMeasurement'),
        ),
        migrations.AddField(
            model_name='hotliquortun',
            name='temperature_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceMeasurement'),
        ),
    ]
