# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0015_auto_20170730_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewhouse',
            name='boil_kettle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.HotLiquorTun'),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='main_pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Pump'),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='mash_tun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.MashTun'),
        ),
        migrations.AlterField(
            model_name='heatingelement',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heatingelement',
            name='rating',
            field=models.FloatField(default=5500.0),
        ),
        migrations.AlterField(
            model_name='hotliquortun',
            name='heating_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.HeatingElement'),
        ),
        migrations.AlterField(
            model_name='hotliquortun',
            name='temperature_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceMeasurement'),
        ),
        migrations.AlterField(
            model_name='hotliquortun',
            name='volume',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='mashtun',
            name='heat_exchanger_conductivity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='mashtun',
            name='temperature_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceMeasurement'),
        ),
        migrations.AlterField(
            model_name='mashtun',
            name='volume',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedevice',
            name='alpha',
            field=models.FloatField(default=0.00385),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedevice',
            name='zero_resistance',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='amplifier_resistance_a',
            field=models.FloatField(default=15000.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='amplifier_resistance_b',
            field=models.FloatField(default=270000.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='offset_resistance_bottom',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='offset_resistance_top',
            field=models.FloatField(default=100000.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='rtd_top_resistance',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedeviceamplifier',
            name='vcc',
            field=models.FloatField(default=3.3),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedevicemeasurement',
            name='amplifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDeviceAmplifier'),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedevicemeasurement',
            name='analog_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resistancetemperaturedevicemeasurement',
            name='rtd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.ResistanceTemperatureDevice'),
        ),
    ]
