# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 03:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0016_auto_20170730_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitteringIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('alpha_acid_weight', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_added', models.CharField(choices=[('0', 'MASH'), ('1', 'BOIL'), ('2', 'WHIRLPOOL'), ('3', 'FERMENTATION'), ('4', 'CONDITIONING')], max_length=1)),
                ('time_added', models.IntegerField(default=0)),
                ('bittering_ingredients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BitteringIngredient')),
            ],
        ),
        migrations.CreateModel(
            name='MaltIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('potential_sg_contribution', models.FloatField(default=1.0, validators=(django.core.validators.MinValueValidator(1.0),))),
                ('color', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredientaddition',
            name='malt_ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.MaltIngredient'),
        ),
        migrations.AddField(
            model_name='ingredientaddition',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe'),
        ),
    ]
