# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('brewery', '0017_auto_20160802_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewhouse',
            name='key',
        ),
        migrations.RemoveField(
            model_name='brewhouse',
            name='secret',
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
