# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0017_auto_20170809_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitteringIngredientAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_added', models.CharField(choices=[('0', 'MASH'), ('1', 'BOIL'), ('2', 'WHIRLPOOL'), ('3', 'FERMENTATION'), ('4', 'CONDITIONING')], max_length=1)),
                ('time_added', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.BitteringIngredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MaltIngredientAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_added', models.CharField(choices=[('0', 'MASH'), ('1', 'BOIL'), ('2', 'WHIRLPOOL'), ('3', 'FERMENTATION'), ('4', 'CONDITIONING')], max_length=1)),
                ('time_added', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.MaltIngredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientaddition',
            name='bittering_ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredientaddition',
            name='malt_ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredientaddition',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='IngredientAddition',
        ),
    ]
