# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0018_auto_20160821_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewhouse',
            name='ec2_instance_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='simulated',
            field=models.BooleanField(default=False),
        ),
    ]
