# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0019_auto_20170813_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitteringingredientaddition',
            name='units',
            field=models.CharField(choices=[('0', 'pounds'), ('1', 'ounces'), ('2', 'grams'), ('3', 'kilograms')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='maltingredientaddition',
            name='units',
            field=models.CharField(choices=[('0', 'pounds'), ('1', 'ounces'), ('2', 'grams'), ('3', 'kilograms')], default='0', max_length=1),
        ),
    ]
