# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0020_auto_20170813_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
