# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 20:42
from __future__ import unicode_literals

from django.db import migrations


def save_brewhouses(apps, schema_editor):
    """Saves all brewhouses to make sure they have their auxiliary equipment
    saved with them like the boil kettle, etc.
    """
    Brewhouse = apps.get_model('brewery', 'Brewhouse')
    for brewhouse in Brewhouse.objects.all():
        brewhouse.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0021_recipe_volume'),
    ]

    operations = [
        migrations.RunPython(save_brewhouses)
    ]
