# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0025_auto_20171119_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsensor',
            name='variable_type',
            field=models.CharField(choices=[('value', 'value'), ('override', 'override')], default='value', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='assetsensor',
            unique_together=set([('name', 'brewhouse', 'variable_type')]),
        ),
    ]
