# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0026_auto_20171119_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewhouse',
            name='simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='simulated_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
