# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0027_auto_20180101_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewhouse',
            name='simulated_uuid',
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='simulated_deployment_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='simulated_secret_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
