# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0029_hop_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeastIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('attenuation', models.FloatField(default=0.0)),
                ('low_temperature', models.FloatField(default=0.0)),
                ('high_temperature', models.FloatField(default=0.0)),
                ('abv_tolerance', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.YeastIngredient'),
        ),
    ]
