# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 21:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0030_auto_20180127_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yeastingredient',
            name='attenuation',
        ),
        migrations.AddField(
            model_name='yeastingredient',
            name='high_attenuation',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='yeastingredient',
            name='low_attenuation',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='yeastingredient',
            name='abv_tolerance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
