# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0039_correct_bjcp_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='brewhouse_efficiency',
            field=models.FloatField(default=1.0),
        ),
    ]
