# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 01:50
from __future__ import unicode_literals

from django.db import migrations


def add_user_preferences(apps, schema_editor):
    """Adds user preferences to all users."""
    User = apps.get_model('auth', 'User')
    UserPreferences = apps.get_model('user', 'UserPreferences')
    for user in User.objects.all():
        UserPreferences.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user_preferences),
    ]
